language: ruby
cache: bundler
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head
script:
  - bundle exec rspec
  - bundle exec codeclimate-test-reporter
addons:
  code_climate:
    repo_token: b1d80c686f42ee5eb66895c4b0ac5c0d978e964d4700eae35aa0138f5a650c02
matrix:
  allow_failures:
    - rvm: ruby-head
