#!/usr/bin/env ruby

dir = File.expand_path('..', __dir__)
$LOAD_PATH.unshift(dir) unless $LOAD_PATH.include?(dir)

require 'rubygems'
require 'routemaster/cli/top_level'

begin
  Routemaster::CLI::Toplevel.new.run(ARGV)
rescue Routemaster::CLI::Exit => e
  exit e.message.to_i
end

